### PR TITLE
Update assistant.py

### PR DESCRIPTION
**Pull request by elblogbruno**
Modified just to play a sound when you say OK Google!

### CODE REVIEW

**Comment by gauravsacc** [comment]
@elblogbruno you also want to push the mod to the assistant.py for the new SDK update?

**Comment by elblogbruno** [comment]
Ok yes I forgot

**Comment by gauravsacc** [comment]
still don't see any changes to fix the compatibility issue

**Comment by gauravsacc** [comment]
@elblogbruno do you want to raise another PR?

**Comment by elblogbruno** [comment]
Sorry I'm still pretty new to GitHub!

**Pull request closed without merging**
